version: "3"
services:
  grafana:
    image: grafana/grafana:7.1.0
    ports:
      - 3000:3000
    volumes:
      - ./dist:/var/lib/grafana/plugins/instana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
  mountebank:
    build: specs/mb
    image: ui-backend-mockserver
    volumes:
      - ./specs/mb/imposters:/imposters
    ports:
      - 2525:2525
      - 8010:8010
