version: "3"
services:
  grafana:
    image: grafana/grafana:6.5.2
    ports:
      - 3000:3000
    volumes:
      - ./dist:/var/lib/grafana/plugins/instana
    links:
      - mountebank
    environment:
      GF_LOG_LEVEL: debug
  mountebank:
    build: specs/mb
    image: ui-backend-mockserver
    ports:
      - 2525:2525
      - 8010:8010
