services:
  grafana:
    user: root
    container_name: 'instana-datasource'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-13.0.2}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/instana-datasource
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/instana-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.instana-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: instana-datasource
